### ISSUE TITLE
Melhorar gitignore

### ISSUE THREAD

**Issue by zidenis** [gabrielsr/bomberman#1]
Ao importar o projeto no eclipse, alguns arquivos foram criados, de forma que fica inviável posterior sincronização. Sugiro adicionar ao .gitignore o seguinte:
# Eclipse

.classpath
.project
.settings/
bin/
# Mac OSX

.DS_Store
.Trashes
# Windows

Thumbs.ini
Desktop.ini

**Comment by gabrielsr** [comment]
Tem as manhas de corrigir e mandar o push?

**Comment by zidenis** [comment]
feito.
