### ISSUE TITLE
Adicionar atributo para coletar Id da entidade que dropou a bomba que causou explosão

### ISSUE THREAD

**Issue by Dayof** [gabrielsr/bomberman#36]
Setar a entidade que dropou a bomba que causou explosão para que o Módulo Score saiba quem destruiu alguma entidade.

Designado para @DRA2840

**Comment by drazevedo** [comment]
Deixa aberto até que o commit realmente entre na base de código @Dayof

**Comment by Dayof** [comment]
Yes Sir!

**Comment by drazevedo** [comment]
Thank you, miss!

**Comment by drazevedo** [comment]
Agora sim, pode fechar, por causa do commit 6e3307273e47a6b4eb2da56a68301c68c7615526
